### ISSUE TITLE
Failed to start GPD Fan Daemon without /var/log/gpdfand

### ISSUE THREAD

**Issue by Redsandro** [efluffy/gpdfand#3]
Brand new GPD Pocket with Ubuntu 16.04 pre-installed.

After `install.sh`:

> Job for gpdfand.service failed because the control process exited with error code. See "systemctl status gpdfand.service" and "journalctl -xe" for details.

Basically the install.sh or readme instructions need a `mkdir -p /var/log/gpdfand`

---

`$ systemctl status gpdfand.service`

```
● gpdfand.service - GPD Fan Daemon
   Loaded: loaded (/etc/systemd/system/gpdfand.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since di 2017-08-22 03:29:58 CEST; 3min 52s ago
  Process: 4760 ExecStart=/usr/local/bin/gpdfand (code=exited, status=2)

aug 22 03:29:58 gpd systemd[1]: Starting GPD Fan Daemon...
aug 22 03:29:58 gpd gpdfand[4760]: Cannot write to '/var/log/gpdfand/gpdfand.log': No such file or directory at /usr/share/perl5/Log/Dispatch/File.pm line 107.
aug 22 03:29:58 gpd systemd[1]: gpdfand.service: Control process exited, code=exited status=2
aug 22 03:29:58 gpd systemd[1]: Failed to start GPD Fan Daemon.
aug 22 03:29:58 gpd systemd[1]: gpdfand.service: Unit entered failed state.
aug 22 03:29:58 gpd systemd[1]: gpdfand.service: Failed with result 'exit-code'.
```

**Comment by stockmind** [comment]
I copy here the Reddit reply:
You can install all of the GPD Fand related files issuing those commands: 

https://github.com/stockmind/gpd-pocket-ubuntu-respin/blob/master/README.md#gpdfand
Using that you can update your GPD fand script with the one rewritten in python by Chrisawcom.

If you are using my scripts you can update/install all of them on your system issuing those commands: https://github.com/stockmind/gpd-pocket-ubuntu-respin/blob/master/README.md#update-script
That will install audio conf, network, bluetooth and rotation scripts.

If you want another approach that has more support at the moment you can follow the Chrisawcom work here: https://github.com/cawilliamson/ansible-gpdpocket

The two approaches are not yet compatible so you have to choose one atm.

**Comment by efluffy** [comment]
Added mkdir to install.sh
