### ISSUE TITLE
GPIO number

### ISSUE THREAD

**Issue by ViktorWalter** [efluffy/gpdfand#7]
I could not find an answer anywhere, so I am bringing it here:
While the current mainline Linux kernel now contains the @jwrdegoede fan driver, that one depends on DPTF being activated, which causes premature freezing for some users. As mentioned in this issue : https://github.com/stockmind/gpd-pocket-ubuntu-respin/issues/111 the original gpdfand method of fan control, derived from your project, which could be a working replacement, does not work anymore in the current kernel. I have been doing some tests and comparing the two methods. It seems that the GPIO pins for the fan are now controlled with the direction output variable. However, using the gpio397 this way (echo out | sudo tee /sys/class/gpio/gpio397/direction) does nothing and with gpio398 the input is refused outright (error 517). My idea is that the newer kernel possibly maps the pins in question to some other GPIO number. 
The gpd pocket fan module (https://github.com/torvalds/linux/blob/master/drivers/platform/x86/gpd-pocket-fan.c) finds the correct gpio pins by matching with the FAN02501 acpi device name, but I don't have the means to retrieve the numbers it found and neither could I find such mapping information in the file system.
May I ask how did you originally find which gpio was the one controlling the fan?
Thank you.

**Comment by efluffy** [comment]
The newer kernel could be hogging those pins which is why they aren't working. May need to unload the fan driver itself.

As for finding the pins originally, it's been awhile and I don't remember exactly how I found the correct one, but ```cat /sys/kernel/debug/gpio``` may help. If it doesn't exist; ```mount -t debugfs debugfs /sys/kernel/debug```

**Comment by ViktorWalter** [comment]
Yes! Thank you, printing that debugging info with the kernel mod loaded solved it. I was right, the new kernel maps the two outputs to gpio341 and gpio342, so to activate them I just had to push these numbers to /sys/class/gpio/export and then set values of gpio341/value and gpio342/value as was done with gpio397 and gpio398 before. May I link the issue in the stockmind respin to this conversation?

**Comment by efluffy** [comment]
Sure, link away,
